feat - first commit diploma project
IlnurNig/java-explore-with-me pull request #1
Opened 2022-10-31 05:41 UTC by IlnurNig

2022-11-01 10:51 UTC, db-exp requested changes

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/compilation/service/CompilationService.java
> +    public Compilation getById(Long id) throws ExceptionNotFound {
нужно будет убрать throws

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/compilation/service/CompilationService.java
> +    public void addEvent(Long eventId, Long compId) throws ExceptionNotFound {
нужно будет убрать throws

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/compilation/service/CompilationService.java
> +    public void deleteEvent(Long eventId, Long compId) throws ExceptionNotFound {
нужно будет убрать throws

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/compilation/service/CompilationService.java
> +    public void pinCompilation(Long compId, boolean pinned) throws ExceptionNotFound {
нужно будет убрать throws

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/event/EventAdminController.java
> +            throws ExceptionNotFound {
нужно будет убрать throws

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/event/EventAdminController.java
> +            throws ExceptionNotFound {
нужно будет убрать throws

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/event/EventAdminController.java
> +            throws ExceptionNotFound {
нужно будет убрать throws

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/event/EventPublicController.java
> +        Criteria criteria = Criteria.builder()
Давай критерий собирать на уровне репозитория или сервиса

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/event/model/Event.java
> +    private String annotation;
Нужно добавить валидацию на Size, null/не null или blank
Валидация на уровне получения объекта и сохранения в бд несут разный смысл, ведь после получения объекта в контроллере он вполне может быть изменен

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/event/model/Event.java
> +    private String title;
Нужно добавить валидацию на Size, null/не null или blank

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/event/model/Event.java
> +    public boolean equals(Object o) {
В рамках диплома не нужно equals/hashCode

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/event/repository/EventRepository.java
> +public interface EventRepository extends JpaRepository<Event, Long> {
Добавь, пожалуйста, аннотацию Repository

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/event/service/EventService.java
> +    public Event cancelEvent(Long userId, Long eventId) throws ExceptionNotFound {
нужно убрать throws

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/event/service/EventService.java
> +    public Event setStateEvent(Long eventId, EventState state) throws ExceptionNotFound {
нужно убрать throws

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/event/service/EventService.java
> +            throws ExceptionNotFound {
нужно убрать throws

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/event/service/EventService.java
> +//        Оставил код закоментированным. Если код раскоментировать не проходят тесты в постман.
Давай либо уберем код и сделаем по-другому, либо починим

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/event/service/EventService.java
> +        Event event = getById(eventId);
Давай искать по БД, то есть getByIdAndUserId (надо реализовать)

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/event/service/EventService.java
> +            throws ExceptionNotFound, ExceptionConflict, ExceptionBadRequest {
нужно убрать throws

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/event/service/EventService.java
> +            throw new ExceptionBadRequest("only the author of the event can confirm the application");
тут должно превращаться в 403 Forbidden

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/participationRequest/ParticipationRequestController.java
> +            throws ExceptionBadRequest, ExceptionNotFound {
нужно убрать throws

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/participationRequest/model/ParticipationRequest.java
> +    public boolean equals(Object o) {
не нужен equals/hashcode для диплома

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/participationRequest/repository/ParticipationRequestRepository.java
> +public interface ParticipationRequestRepository extends JpaRepository<ParticipationRequest, Long> {
Добавь, пожалуйста, аннотацию Repository

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/participationRequest/service/ParticipationRequestService.java
> +    public ParticipationRequest create(ParticipationRequest request) throws ExceptionConflict {
нужно убрать throws

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/participationRequest/service/ParticipationRequestService.java
> +    public ParticipationRequest getById(Long id) throws ExceptionNotFound {
нужно убрать throws

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/participationRequest/service/ParticipationRequestService.java
> +    public ParticipationRequest cancel(Long requestId, Long userId) throws ExceptionNotFound, ExceptionBadRequest {
нужно убрать throws

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/statsClient/StatsClient.java
> +        return new ArrayList<>();
Можно List.of(), чтобы неизменяемый список вернуть

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/statsClient/dto/EndpointHit.java
> +    private String app;
Давай добавим ограничения на размер Size

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/statsClient/dto/EndpointHit.java
> +    private String uri;
Давай добавим ограничения на размер Size

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/statsClient/dto/ViewStats.java
> +    public boolean equals(Object o) {
В дипломе не нужно реализовывать equals и hashcode

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/user/UserController.java
> +    public UserDto create(@Valid @RequestBody UserDto userDto) throws ExceptionConflict {
Нужно убрать throws

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/user/UserController.java
> +    public void delete(@PathVariable @NotNull Long id) throws ExceptionNotFound {
Нужно убрать throws

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/user/model/User.java
> +    private String name;
Давай добавим проверку на размер, null/не null

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/user/model/User.java
> +    private String email;
Давай добавим проверку на размер, null/не null

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/user/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
Добавь, пожалуйста, Repository

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/user/service/UserService.java
> +    public User createUser(User user) throws ExceptionConflict {
нужно убрать throws

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/user/service/UserService.java
> +    public User getById(long id) throws ExceptionNotFound {
нужно убрать throws

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/java/ru/practicum/user/service/UserService.java
> +    public void deleteUser(Long id) throws ExceptionNotFound {
нужно убрать throws

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/resources/schema.sql
> +    name TEXT                                    NOT NULL,
нужно добавить размер колонки, text слишком много для name, кажется, тут хватит varchar(128/256)

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/resources/schema.sql
> +    name  TEXT                                    NOT NULL,
нужно добавить размер колонки, text слишком много для name, кажется, тут хватит varchar(128/256)

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/resources/schema.sql
> +    email TEXT                                    NOT NULL,
нужно добавить размер колонки, text слишком много, кажется, тут хватит varchar(128/256)

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/resources/schema.sql
> +    state              TEXT,
нужно добавить размер колонки, text слишком много, кажется, тут хватит varchar(50)

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/resources/schema.sql
> +    title              TEXT,
нужно добавить размер колонки, text слишком много, кажется, тут хватит varchar(128/256)

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/resources/schema.sql
> +    state        TEXT,
нужно добавить размер колонки, text слишком много, кажется, тут хватит varchar(50)

2022-11-01 10:51 UTC, db-exp commented on ewm/src/main/resources/schema.sql
> +    title  TEXT,
нужно добавить размер колонки, text слишком много, кажется, тут хватит varchar(128/256)

2022-11-01 10:51 UTC, db-exp commented on stats/pom.xml
> +    <dependencies>
версии должны быть в dependancyManagement

2022-11-01 10:51 UTC, db-exp commented on stats/src/main/java/ru/practicum/dto/EndpointHit.java
> +    private String uri;
Давай добавим проверку на размер

2022-11-01 10:51 UTC, db-exp commented on stats/src/main/java/ru/practicum/dto/EndpointHit.java
> +    private String app;
Давай добавим проверку на размер

2022-11-01 10:51 UTC, db-exp commented on stats/src/main/java/ru/practicum/dto/ViewStats.java
> +    public boolean equals(Object o) {
В рамках диплома не нужно equals/hashcode

2022-11-01 10:51 UTC, db-exp commented on stats/src/main/java/ru/practicum/model/Stats.java
> +    private String app;
Давай добавим валиацию размера/null/не null или blank

2022-11-01 10:51 UTC, db-exp commented on stats/src/main/java/ru/practicum/model/Stats.java
> +    private String uri;
Давай добавим валиацию размера/null/не null или blank

2022-11-01 10:51 UTC, db-exp commented on stats/src/main/java/ru/practicum/model/Stats.java
> +    private String ip;
Давай добавим валиацию размера/null/не null или blank

2022-11-01 10:51 UTC, db-exp commented on stats/src/main/java/ru/practicum/repository/StatsRepository.java
> +public interface StatsRepository extends JpaRepository<Stats, Long> {
давай добавить аннотацию Repository

2022-11-01 10:51 UTC, db-exp commented on stats/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS stats
TEXT слишком много, давай сделаем varchar с размерностью

2022-11-02 09:05 UTC, IlnurNig commented on checkstyle.xml
> +<!--		<module name="RightCurly">-->
классы генерируемые мапстрак не проходили проверку чекстайл. Добавлял suppressions.xml. Но не помогло

2022-11-02 09:28 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/exception/exceptionClass/ExceptionNotFound.java
> +public class ExceptionNotFound extends Exception {
исправлено

2022-11-02 09:28 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/exception/exceptionClass/ExceptionInteralServerError.java
> +public class ExceptionInteralServerError extends Exception {
исправлено

2022-11-02 09:28 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/exception/exceptionClass/ExceptionConflict.java
> +public class ExceptionConflict extends Exception {
иправлено

2022-11-02 09:29 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/category/CategoryAdminController.java
> +    public void delete(@PathVariable @NotNull Long id) throws ExceptionNotFound {
исправлено

2022-11-02 09:29 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/category/CategoryAdminController.java
> +    public CategoryDto update(@Valid @RequestBody CategoryDto categoryDto) throws ExceptionNotFound {
исправлено

2022-11-02 09:29 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/category/CategoryPublicController.java
> +    public CategoryDto getById(@PathVariable @NotNull Long catId) throws ExceptionNotFound {
исправлено

2022-11-02 09:30 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/category/dto/CategoryDto.java
> +    private Long id;
исправлено

2022-11-02 09:32 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/category/dto/CategoryMapper.java
> +@Mapper(componentModel = "spring")
В первый раз использовал мапстрак. Еще не полностью изучил. С Uses пока что не получилось сделать. Оставил без изменений.

2022-11-02 09:33 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/category/model/Category.java
> +    private String name;
исправлено

2022-11-02 09:39 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/category/repository/CategoryRepository.java
> +public interface CategoryRepository extends JpaRepository<Category, Long> {
.добавил.

2022-11-02 09:39 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/category/service/CategoryService.java
> +    public Category update(Category category) throws ExceptionNotFound {
исправлено

2022-11-02 09:39 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/category/service/CategoryService.java
> +    public Category getById(Long id) throws ExceptionNotFound {
исправлено

2022-11-02 09:40 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/category/service/CategoryService.java
> +    public void delete(Long id) throws ExceptionNotFound {
исправлено

2022-11-02 09:40 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/category/service/CategoryService.java
> +    private void validateId(long id) throws ExceptionNotFound {
исправлено

2022-11-02 09:40 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/compilation/CompilationAdminController.java
> +                         @PathVariable @NotNull Long compId) throws ExceptionNotFound {
исправлено

2022-11-02 09:40 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/compilation/CompilationAdminController.java
> +    public void unpin(@PathVariable @NotNull Long compId) throws ExceptionNotFound {
исправлено

2022-11-02 09:40 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/compilation/CompilationAdminController.java
> +    public void pin(@PathVariable @NotNull Long compId) throws ExceptionNotFound {
исправлено

2022-11-02 09:41 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/compilation/CompilationPublicController.java
> +    public CompilationDto get(@PathVariable @NotNull Long id) throws ExceptionNotFound {
исправлено

2022-11-02 09:44 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/compilation/dto/NewCompilationDto.java
> +    private String title;
исправлено

2022-11-02 09:45 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/compilation/model/Compilation.java
> +    private String title;
исправлено

2022-11-02 09:46 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/compilation/model/Compilation.java
> +    public boolean equals(Object o) {
исправлено

2022-11-02 09:47 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/compilation/repository/CompilationRepository.java
> +public interface CompilationRepository extends JpaRepository<Compilation, Long> {
добавлено

2022-11-02 09:47 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/compilation/service/CompilationService.java
> +    public Compilation getById(Long id) throws ExceptionNotFound {
исправлено

2022-11-02 09:47 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/compilation/service/CompilationService.java
> +    public void addEvent(Long eventId, Long compId) throws ExceptionNotFound {
исправлено

2022-11-02 09:47 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/compilation/service/CompilationService.java
> +    public void deleteEvent(Long eventId, Long compId) throws ExceptionNotFound {
исправлено

2022-11-02 09:48 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/compilation/service/CompilationService.java
> +    public void pinCompilation(Long compId, boolean pinned) throws ExceptionNotFound {
исправлено

2022-11-02 09:48 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/event/EventAdminController.java
> +            throws ExceptionNotFound {
исправлено

2022-11-02 09:48 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/event/EventAdminController.java
> +            throws ExceptionNotFound {
исправлено

2022-11-02 09:48 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/event/EventAdminController.java
> +            throws ExceptionNotFound {
исправлено

2022-11-02 10:06 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/event/EventPublicController.java
> +        Criteria criteria = Criteria.builder()
задумка была что вместо 9 переменных в метод передавать один объект с критерием. К тому же если перенести сборку объекта критерия в сервис, то в сервисе вместо одного метода будет 2, под каждый контроллер которые передают разные критерии. Предлагаю оставить.

2022-11-02 10:09 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/event/model/Event.java
> +    private String annotation;
исправлено

2022-11-02 10:10 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/event/model/Event.java
> +    private String title;
исправлено

2022-11-02 10:10 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/event/model/Event.java
> +    public boolean equals(Object o) {
исправлено

2022-11-02 10:11 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/event/repository/EventRepository.java
> +public interface EventRepository extends JpaRepository<Event, Long> {
исправлено

2022-11-02 10:12 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/event/service/EventService.java
> +    public Event cancelEvent(Long userId, Long eventId) throws ExceptionNotFound {
исправлено

2022-11-02 10:12 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/event/service/EventService.java
> +    public Event setStateEvent(Long eventId, EventState state) throws ExceptionNotFound {
исправлено

2022-11-02 10:12 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/event/service/EventService.java
> +            throws ExceptionNotFound {
исправлено

2022-11-02 10:13 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/event/service/EventService.java
> +//        Оставил код закоментированным. Если код раскоментировать не проходят тесты в постман.
исправлено

2022-11-02 10:17 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/event/service/EventService.java
> +            throws ExceptionNotFound, ExceptionConflict, ExceptionBadRequest {
исправлено

2022-11-02 10:19 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/event/service/EventService.java
> +        Event event = getById(eventId);
исправлено

2022-11-02 10:27 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/event/service/EventService.java
> +            throw new ExceptionBadRequest("only the author of the event can confirm the application");
исправлено

2022-11-02 10:27 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/participationRequest/ParticipationRequestController.java
> +            throws ExceptionBadRequest, ExceptionNotFound {
исправлено

2022-11-02 10:28 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/participationRequest/model/ParticipationRequest.java
> +    public boolean equals(Object o) {
исправлено

2022-11-02 10:29 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/participationRequest/repository/ParticipationRequestRepository.java
> +public interface ParticipationRequestRepository extends JpaRepository<ParticipationRequest, Long> {
исправлено

2022-11-02 10:29 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/participationRequest/service/ParticipationRequestService.java
> +    public ParticipationRequest create(ParticipationRequest request) throws ExceptionConflict {
исправлено

2022-11-02 10:29 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/participationRequest/service/ParticipationRequestService.java
> +    public ParticipationRequest getById(Long id) throws ExceptionNotFound {
исправлено

2022-11-02 10:31 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/statsClient/StatsClient.java
> +        return new ArrayList<>();
исправлено

2022-11-02 10:32 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/statsClient/dto/EndpointHit.java
> +    private String app;
исправлено

2022-11-02 10:32 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/statsClient/dto/EndpointHit.java
> +    private String uri;
исправлено

2022-11-02 10:33 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/statsClient/dto/ViewStats.java
> +    public boolean equals(Object o) {
исправлено

2022-11-02 10:33 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/user/UserController.java
> +    public UserDto create(@Valid @RequestBody UserDto userDto) throws ExceptionConflict {
исправлено

2022-11-02 10:33 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/user/UserController.java
> +    public void delete(@PathVariable @NotNull Long id) throws ExceptionNotFound {
исправлено

2022-11-02 10:34 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/user/model/User.java
> +    private String name;
исправлено

2022-11-02 10:34 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/user/model/User.java
> +    private String email;
исправлено

2022-11-02 10:35 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/user/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
исправлено

2022-11-02 10:35 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/user/service/UserService.java
> +    public User createUser(User user) throws ExceptionConflict {
исправлено

2022-11-02 10:35 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/user/service/UserService.java
> +    public User getById(long id) throws ExceptionNotFound {
исправлено

2022-11-02 10:35 UTC, IlnurNig commented on ewm/src/main/java/ru/practicum/user/service/UserService.java
> +    public void deleteUser(Long id) throws ExceptionNotFound {
исправлено

2022-11-02 10:36 UTC, IlnurNig commented on ewm/src/main/resources/schema.sql
> +    name TEXT                                    NOT NULL,
исправлено

2022-11-02 10:39 UTC, IlnurNig commented on ewm/src/main/resources/schema.sql
> +    name  TEXT                                    NOT NULL,
исправлено

2022-11-02 10:39 UTC, IlnurNig commented on ewm/src/main/resources/schema.sql
> +    email TEXT                                    NOT NULL,
исправлено

2022-11-02 10:40 UTC, IlnurNig commented on ewm/src/main/resources/schema.sql
> +    state              TEXT,
исправлено

2022-11-02 10:40 UTC, IlnurNig commented on ewm/src/main/resources/schema.sql
> +    title              TEXT,
исправлено

2022-11-02 15:40 UTC, IlnurNig commented on ewm/src/main/resources/schema.sql
> +    state        TEXT,
исправлено

2022-11-02 15:45 UTC, IlnurNig commented on stats/src/main/java/ru/practicum/dto/EndpointHit.java
> +    private String app;
исправлено

2022-11-02 15:45 UTC, IlnurNig commented on stats/src/main/java/ru/practicum/dto/ViewStats.java
> +    public boolean equals(Object o) {
исправлено

2022-11-02 15:46 UTC, IlnurNig commented on stats/src/main/java/ru/practicum/model/Stats.java
> +    private String app;
исправлено

2022-11-02 15:46 UTC, IlnurNig commented on stats/src/main/java/ru/practicum/model/Stats.java
> +    private String uri;
исправлено

2022-11-02 15:47 UTC, IlnurNig commented on stats/src/main/java/ru/practicum/model/Stats.java
> +    private String ip;
исправлено

2022-11-02 15:47 UTC, IlnurNig commented on stats/src/main/java/ru/practicum/repository/StatsRepository.java
> +public interface StatsRepository extends JpaRepository<Stats, Long> {
исправлено

2022-11-02 19:36 UTC, db-exp commented on ewm/src/main/java/ru/practicum/event/EventPublicController.java
> +        Criteria criteria = Criteria.builder()
ок

2022-11-02 19:45 UTC, db-exp approved these changes

2022-11-05 05:30 UTC, merged